/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeferredResultResponseEntity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DeferredResultResponseEntity'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.RpcControllerApi = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.DeferredResultResponseEntity);
  }
}(this, function(ApiClient, DeferredResultResponseEntity) {
  'use strict';

  /**
   * RpcController service.
   * @module api/RpcControllerApi
   * @version 2.0
   */

  /**
   * Constructs a new RpcControllerApi. 
   * @alias module:api/RpcControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the handleOneWayDeviceRPCRequestUsingPOST operation.
     * @callback module:api/RpcControllerApi~handleOneWayDeviceRPCRequestUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeferredResultResponseEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * handleOneWayDeviceRPCRequest
     * @param {String} deviceId deviceId
     * @param {String} requestBody requestBody
     * @param {module:api/RpcControllerApi~handleOneWayDeviceRPCRequestUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeferredResultResponseEntity}
     */
    this.handleOneWayDeviceRPCRequestUsingPOST = function(deviceId, requestBody, callback) {
      var postBody = requestBody;

      // verify the required parameter 'deviceId' is set
      if (deviceId === undefined || deviceId === null) {
        throw new Error("Missing the required parameter 'deviceId' when calling handleOneWayDeviceRPCRequestUsingPOST");
      }

      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling handleOneWayDeviceRPCRequestUsingPOST");
      }


      var pathParams = {
        'deviceId': deviceId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['X-Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = DeferredResultResponseEntity;

      return this.apiClient.callApi(
        '/api/plugins/rpc/oneway/{deviceId}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the handleTwoWayDeviceRPCRequestUsingPOST operation.
     * @callback module:api/RpcControllerApi~handleTwoWayDeviceRPCRequestUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeferredResultResponseEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * handleTwoWayDeviceRPCRequest
     * @param {String} deviceId deviceId
     * @param {String} requestBody requestBody
     * @param {module:api/RpcControllerApi~handleTwoWayDeviceRPCRequestUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeferredResultResponseEntity}
     */
    this.handleTwoWayDeviceRPCRequestUsingPOST = function(deviceId, requestBody, callback) {
      var postBody = requestBody;

      // verify the required parameter 'deviceId' is set
      if (deviceId === undefined || deviceId === null) {
        throw new Error("Missing the required parameter 'deviceId' when calling handleTwoWayDeviceRPCRequestUsingPOST");
      }

      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling handleTwoWayDeviceRPCRequestUsingPOST");
      }


      var pathParams = {
        'deviceId': deviceId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['X-Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = DeferredResultResponseEntity;

      return this.apiClient.callApi(
        '/api/plugins/rpc/twoway/{deviceId}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
