/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AlarmId', 'model/EntityId', 'model/TenantId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AlarmId'), require('./EntityId'), require('./TenantId'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.AlarmInfo = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.AlarmId, root.ThingsboardRestApi.EntityId, root.ThingsboardRestApi.TenantId);
  }
}(this, function(ApiClient, AlarmId, EntityId, TenantId) {
  'use strict';




  /**
   * The AlarmInfo model module.
   * @module model/AlarmInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>AlarmInfo</code>.
   * @alias module:model/AlarmInfo
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>AlarmInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlarmInfo} obj Optional instance to populate.
   * @return {module:model/AlarmInfo} The populated <code>AlarmInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ackTs')) {
        obj['ackTs'] = ApiClient.convertToType(data['ackTs'], 'Number');
      }
      if (data.hasOwnProperty('clearTs')) {
        obj['clearTs'] = ApiClient.convertToType(data['clearTs'], 'Number');
      }
      if (data.hasOwnProperty('createdTime')) {
        obj['createdTime'] = ApiClient.convertToType(data['createdTime'], 'Number');
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], 'String');
      }
      if (data.hasOwnProperty('endTs')) {
        obj['endTs'] = ApiClient.convertToType(data['endTs'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = AlarmId.constructFromObject(data['id']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('originator')) {
        obj['originator'] = EntityId.constructFromObject(data['originator']);
      }
      if (data.hasOwnProperty('originatorName')) {
        obj['originatorName'] = ApiClient.convertToType(data['originatorName'], 'String');
      }
      if (data.hasOwnProperty('propagate')) {
        obj['propagate'] = ApiClient.convertToType(data['propagate'], 'Boolean');
      }
      if (data.hasOwnProperty('severity')) {
        obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
      }
      if (data.hasOwnProperty('startTs')) {
        obj['startTs'] = ApiClient.convertToType(data['startTs'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('tenantId')) {
        obj['tenantId'] = TenantId.constructFromObject(data['tenantId']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} ackTs
   */
  exports.prototype['ackTs'] = undefined;
  /**
   * @member {Number} clearTs
   */
  exports.prototype['clearTs'] = undefined;
  /**
   * @member {Number} createdTime
   */
  exports.prototype['createdTime'] = undefined;
  /**
   * @member {String} details
   */
  exports.prototype['details'] = undefined;
  /**
   * @member {Number} endTs
   */
  exports.prototype['endTs'] = undefined;
  /**
   * @member {module:model/AlarmId} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/EntityId} originator
   */
  exports.prototype['originator'] = undefined;
  /**
   * @member {String} originatorName
   */
  exports.prototype['originatorName'] = undefined;
  /**
   * @member {Boolean} propagate
   */
  exports.prototype['propagate'] = undefined;
  /**
   * @member {module:model/AlarmInfo.SeverityEnum} severity
   */
  exports.prototype['severity'] = undefined;
  /**
   * @member {Number} startTs
   */
  exports.prototype['startTs'] = undefined;
  /**
   * @member {module:model/AlarmInfo.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/TenantId} tenantId
   */
  exports.prototype['tenantId'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>severity</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SeverityEnum = {
    /**
     * value: "CRITICAL"
     * @const
     */
    "CRITICAL": "CRITICAL",
    /**
     * value: "MAJOR"
     * @const
     */
    "MAJOR": "MAJOR",
    /**
     * value: "MINOR"
     * @const
     */
    "MINOR": "MINOR",
    /**
     * value: "WARNING"
     * @const
     */
    "WARNING": "WARNING",
    /**
     * value: "INDETERMINATE"
     * @const
     */
    "INDETERMINATE": "INDETERMINATE"  };

  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "ACTIVE_UNACK"
     * @const
     */
    "ACTIVE_UNACK": "ACTIVE_UNACK",
    /**
     * value: "ACTIVE_ACK"
     * @const
     */
    "ACTIVE_ACK": "ACTIVE_ACK",
    /**
     * value: "CLEARED_UNACK"
     * @const
     */
    "CLEARED_UNACK": "CLEARED_UNACK",
    /**
     * value: "CLEARED_ACK"
     * @const
     */
    "CLEARED_ACK": "CLEARED_ACK"  };


  return exports;
}));


