/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuditLogId', 'model/CustomerId', 'model/EntityId', 'model/TenantId', 'model/UserId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AuditLogId'), require('./CustomerId'), require('./EntityId'), require('./TenantId'), require('./UserId'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.AuditLog = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.AuditLogId, root.ThingsboardRestApi.CustomerId, root.ThingsboardRestApi.EntityId, root.ThingsboardRestApi.TenantId, root.ThingsboardRestApi.UserId);
  }
}(this, function(ApiClient, AuditLogId, CustomerId, EntityId, TenantId, UserId) {
  'use strict';




  /**
   * The AuditLog model module.
   * @module model/AuditLog
   * @version 2.0
   */

  /**
   * Constructs a new <code>AuditLog</code>.
   * @alias module:model/AuditLog
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>AuditLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuditLog} obj Optional instance to populate.
   * @return {module:model/AuditLog} The populated <code>AuditLog</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('actionData')) {
        obj['actionData'] = ApiClient.convertToType(data['actionData'], 'String');
      }
      if (data.hasOwnProperty('actionFailureDetails')) {
        obj['actionFailureDetails'] = ApiClient.convertToType(data['actionFailureDetails'], 'String');
      }
      if (data.hasOwnProperty('actionStatus')) {
        obj['actionStatus'] = ApiClient.convertToType(data['actionStatus'], 'String');
      }
      if (data.hasOwnProperty('actionType')) {
        obj['actionType'] = ApiClient.convertToType(data['actionType'], 'String');
      }
      if (data.hasOwnProperty('createdTime')) {
        obj['createdTime'] = ApiClient.convertToType(data['createdTime'], 'Number');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = CustomerId.constructFromObject(data['customerId']);
      }
      if (data.hasOwnProperty('entityId')) {
        obj['entityId'] = EntityId.constructFromObject(data['entityId']);
      }
      if (data.hasOwnProperty('entityName')) {
        obj['entityName'] = ApiClient.convertToType(data['entityName'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = AuditLogId.constructFromObject(data['id']);
      }
      if (data.hasOwnProperty('tenantId')) {
        obj['tenantId'] = TenantId.constructFromObject(data['tenantId']);
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = UserId.constructFromObject(data['userId']);
      }
      if (data.hasOwnProperty('userName')) {
        obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} actionData
   */
  exports.prototype['actionData'] = undefined;
  /**
   * @member {String} actionFailureDetails
   */
  exports.prototype['actionFailureDetails'] = undefined;
  /**
   * @member {module:model/AuditLog.ActionStatusEnum} actionStatus
   */
  exports.prototype['actionStatus'] = undefined;
  /**
   * @member {module:model/AuditLog.ActionTypeEnum} actionType
   */
  exports.prototype['actionType'] = undefined;
  /**
   * @member {Number} createdTime
   */
  exports.prototype['createdTime'] = undefined;
  /**
   * @member {module:model/CustomerId} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {module:model/EntityId} entityId
   */
  exports.prototype['entityId'] = undefined;
  /**
   * @member {String} entityName
   */
  exports.prototype['entityName'] = undefined;
  /**
   * @member {module:model/AuditLogId} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/TenantId} tenantId
   */
  exports.prototype['tenantId'] = undefined;
  /**
   * @member {module:model/UserId} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} userName
   */
  exports.prototype['userName'] = undefined;


  /**
   * Allowed values for the <code>actionStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ActionStatusEnum = {
    /**
     * value: "SUCCESS"
     * @const
     */
    "SUCCESS": "SUCCESS",
    /**
     * value: "FAILURE"
     * @const
     */
    "FAILURE": "FAILURE"  };

  /**
   * Allowed values for the <code>actionType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ActionTypeEnum = {
    /**
     * value: "ADDED"
     * @const
     */
    "ADDED": "ADDED",
    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED",
    /**
     * value: "UPDATED"
     * @const
     */
    "UPDATED": "UPDATED",
    /**
     * value: "ATTRIBUTES_UPDATED"
     * @const
     */
    "ATTRIBUTES_UPDATED": "ATTRIBUTES_UPDATED",
    /**
     * value: "ATTRIBUTES_DELETED"
     * @const
     */
    "ATTRIBUTES_DELETED": "ATTRIBUTES_DELETED",
    /**
     * value: "TIMESERIES_DELETED"
     * @const
     */
    "TIMESERIES_DELETED": "TIMESERIES_DELETED",
    /**
     * value: "RPC_CALL"
     * @const
     */
    "RPC_CALL": "RPC_CALL",
    /**
     * value: "CREDENTIALS_UPDATED"
     * @const
     */
    "CREDENTIALS_UPDATED": "CREDENTIALS_UPDATED",
    /**
     * value: "ASSIGNED_TO_CUSTOMER"
     * @const
     */
    "ASSIGNED_TO_CUSTOMER": "ASSIGNED_TO_CUSTOMER",
    /**
     * value: "UNASSIGNED_FROM_CUSTOMER"
     * @const
     */
    "UNASSIGNED_FROM_CUSTOMER": "UNASSIGNED_FROM_CUSTOMER",
    /**
     * value: "ACTIVATED"
     * @const
     */
    "ACTIVATED": "ACTIVATED",
    /**
     * value: "SUSPENDED"
     * @const
     */
    "SUSPENDED": "SUSPENDED",
    /**
     * value: "CREDENTIALS_READ"
     * @const
     */
    "CREDENTIALS_READ": "CREDENTIALS_READ",
    /**
     * value: "ATTRIBUTES_READ"
     * @const
     */
    "ATTRIBUTES_READ": "ATTRIBUTES_READ",
    /**
     * value: "RELATION_ADD_OR_UPDATE"
     * @const
     */
    "RELATION_ADD_OR_UPDATE": "RELATION_ADD_OR_UPDATE",
    /**
     * value: "RELATION_DELETED"
     * @const
     */
    "RELATION_DELETED": "RELATION_DELETED",
    /**
     * value: "RELATIONS_DELETED"
     * @const
     */
    "RELATIONS_DELETED": "RELATIONS_DELETED",
    /**
     * value: "ALARM_ACK"
     * @const
     */
    "ALARM_ACK": "ALARM_ACK",
    /**
     * value: "ALARM_CLEAR"
     * @const
     */
    "ALARM_CLEAR": "ALARM_CLEAR"  };


  return exports;
}));


