/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityTypeFilter', 'model/RelationsSearchParameters'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityTypeFilter'), require('./RelationsSearchParameters'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.EntityRelationsQuery = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.EntityTypeFilter, root.ThingsboardRestApi.RelationsSearchParameters);
  }
}(this, function(ApiClient, EntityTypeFilter, RelationsSearchParameters) {
  'use strict';




  /**
   * The EntityRelationsQuery model module.
   * @module model/EntityRelationsQuery
   * @version 2.0
   */

  /**
   * Constructs a new <code>EntityRelationsQuery</code>.
   * @alias module:model/EntityRelationsQuery
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>EntityRelationsQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntityRelationsQuery} obj Optional instance to populate.
   * @return {module:model/EntityRelationsQuery} The populated <code>EntityRelationsQuery</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('filters')) {
        obj['filters'] = ApiClient.convertToType(data['filters'], [EntityTypeFilter]);
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = RelationsSearchParameters.constructFromObject(data['parameters']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/EntityTypeFilter>} filters
   */
  exports.prototype['filters'] = undefined;
  /**
   * @member {module:model/RelationsSearchParameters} parameters
   */
  exports.prototype['parameters'] = undefined;



  return exports;
}));


