/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NodeConnectionInfo', 'model/RuleChainConnectionInfo', 'model/RuleChainId', 'model/RuleNode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NodeConnectionInfo'), require('./RuleChainConnectionInfo'), require('./RuleChainId'), require('./RuleNode'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.RuleChainMetaData = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.NodeConnectionInfo, root.ThingsboardRestApi.RuleChainConnectionInfo, root.ThingsboardRestApi.RuleChainId, root.ThingsboardRestApi.RuleNode);
  }
}(this, function(ApiClient, NodeConnectionInfo, RuleChainConnectionInfo, RuleChainId, RuleNode) {
  'use strict';




  /**
   * The RuleChainMetaData model module.
   * @module model/RuleChainMetaData
   * @version 2.0
   */

  /**
   * Constructs a new <code>RuleChainMetaData</code>.
   * @alias module:model/RuleChainMetaData
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>RuleChainMetaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RuleChainMetaData} obj Optional instance to populate.
   * @return {module:model/RuleChainMetaData} The populated <code>RuleChainMetaData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('connections')) {
        obj['connections'] = ApiClient.convertToType(data['connections'], [NodeConnectionInfo]);
      }
      if (data.hasOwnProperty('firstNodeIndex')) {
        obj['firstNodeIndex'] = ApiClient.convertToType(data['firstNodeIndex'], 'Number');
      }
      if (data.hasOwnProperty('nodes')) {
        obj['nodes'] = ApiClient.convertToType(data['nodes'], [RuleNode]);
      }
      if (data.hasOwnProperty('ruleChainConnections')) {
        obj['ruleChainConnections'] = ApiClient.convertToType(data['ruleChainConnections'], [RuleChainConnectionInfo]);
      }
      if (data.hasOwnProperty('ruleChainId')) {
        obj['ruleChainId'] = RuleChainId.constructFromObject(data['ruleChainId']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/NodeConnectionInfo>} connections
   */
  exports.prototype['connections'] = undefined;
  /**
   * @member {Number} firstNodeIndex
   */
  exports.prototype['firstNodeIndex'] = undefined;
  /**
   * @member {Array.<module:model/RuleNode>} nodes
   */
  exports.prototype['nodes'] = undefined;
  /**
   * @member {Array.<module:model/RuleChainConnectionInfo>} ruleChainConnections
   */
  exports.prototype['ruleChainConnections'] = undefined;
  /**
   * @member {module:model/RuleChainId} ruleChainId
   */
  exports.prototype['ruleChainId'] = undefined;



  return exports;
}));


