/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RuleChainId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RuleChainId'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.RuleChainConnectionInfo = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.RuleChainId);
  }
}(this, function(ApiClient, RuleChainId) {
  'use strict';




  /**
   * The RuleChainConnectionInfo model module.
   * @module model/RuleChainConnectionInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>RuleChainConnectionInfo</code>.
   * @alias module:model/RuleChainConnectionInfo
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>RuleChainConnectionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RuleChainConnectionInfo} obj Optional instance to populate.
   * @return {module:model/RuleChainConnectionInfo} The populated <code>RuleChainConnectionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('additionalInfo')) {
        obj['additionalInfo'] = ApiClient.convertToType(data['additionalInfo'], 'String');
      }
      if (data.hasOwnProperty('fromIndex')) {
        obj['fromIndex'] = ApiClient.convertToType(data['fromIndex'], 'Number');
      }
      if (data.hasOwnProperty('targetRuleChainId')) {
        obj['targetRuleChainId'] = RuleChainId.constructFromObject(data['targetRuleChainId']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} additionalInfo
   */
  exports.prototype['additionalInfo'] = undefined;
  /**
   * @member {Number} fromIndex
   */
  exports.prototype['fromIndex'] = undefined;
  /**
   * @member {module:model/RuleChainId} targetRuleChainId
   */
  exports.prototype['targetRuleChainId'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


