/**
 * Thingsboard REST API
 * For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.
 *
 * OpenAPI spec version: 2.0
 * Contact: info@thingsboard.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomerId'));
  } else {
    // Browser globals (root is window)
    if (!root.ThingsboardRestApi) {
      root.ThingsboardRestApi = {};
    }
    root.ThingsboardRestApi.ShortCustomerInfo = factory(root.ThingsboardRestApi.ApiClient, root.ThingsboardRestApi.CustomerId);
  }
}(this, function(ApiClient, CustomerId) {
  'use strict';




  /**
   * The ShortCustomerInfo model module.
   * @module model/ShortCustomerInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>ShortCustomerInfo</code>.
   * @alias module:model/ShortCustomerInfo
   * @class
   * @param isPublic {Boolean} 
   */
  var exports = function(isPublic) {
    var _this = this;




    _this['isPublic'] = isPublic;
  };

  /**
   * Constructs a <code>ShortCustomerInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShortCustomerInfo} obj Optional instance to populate.
   * @return {module:model/ShortCustomerInfo} The populated <code>ShortCustomerInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = CustomerId.constructFromObject(data['customerId']);
      }
      if (data.hasOwnProperty('public')) {
        obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('isPublic')) {
        obj['isPublic'] = ApiClient.convertToType(data['isPublic'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CustomerId} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {Boolean} public
   */
  exports.prototype['public'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Boolean} isPublic
   */
  exports.prototype['isPublic'] = undefined;



  return exports;
}));


